### ISSUE TITLE
Messages in Flight problem

### ISSUE THREAD

**Issue by mykyypl** [bbc/sqs-consumer#105]
Hello, I have a problem with sqs. 100 messages have been generated, sqs-consumer starts, of which about 10 are removed and the rest goes to Messages in Flight and returns to Messages Available any time. Stops sqs-consumer then starts again and also about 10 goes down and the rest repeats itself.

on the older version 3.6.0
```
/home/project/node/packages/websocket/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: spawn E2BIG
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Object.exports.execFile (child_process.js:143:15)
    at Object.exports.exec (child_process.js:103:18)
    at Consumer.handleMessage (/home/project/node/packages/websocket/sqsworkers.js:54:16)
    at handleMessage (/home/project/node/packages/websocket/node_modules/sqs-consumer/index.js:154:16)
    at /home/project/node/packages/websocket/node_modules/sqs-consumer/node_modules/async/dist/async.js:3830:24
    at replenish (/home/project/node/packages/websocket/node_modules/sqs-consumer/node_modules/async/dist/async.js:946:17)
    at /home/project/node/packages/websocket/node_modules/sqs-consumer/node_modules/async/dist/async.js:950:9
```

**Comment by nspragg** [comment]
@mykyypl - can you provide us with the sqs consumer code you are running?

**Comment by mykyypl** [comment]
my code:
```
const app = Consumer.create({
    queueUrl: 'https://sqs.eu-west-1.amazonaws.com/111111111111/'+namesqs,
    handleMessage: (message, done) => {
        console.log(serverInfo.queuename+ ' get message ' + 'str.length = ' + message.Body.length),

            argsString += ' --input=\'' + encodeURIComponent(message.Body).replace(/'/g, "&#39;") + '\'';
            argsString += ' --profile=' + profile;
            argsString += ' --queuename=' + namesqs;

        var execString = config.phpExecutablePath + ' ' + config.nodeStuffScriptPath + " " + argsString;
        runner.exec(execString, function(err, phpResponse, stderr)
        {
            if(err)
            {
                console.log(err);
                console.log(stderr);
                console.log(phpResponse);
                return;
            }
        });
        done();
    },
    sqs: new AWS.SQS()
});
```

**Comment by nspragg** [comment]
I suspect this is related specifically to the logic within the `handleMessage` fn rather than an SQS consumer issue. 

I recommend focusing on the child_process call. Try executing this code independently of sqs consumer with sample test data (messages) to aid debugging.  

Spawn E2BIG seems to be related to:
https://github.com/nodejs/node/blob/e49429ebd2fe0b7c24e2ee533311dd97f6febd1f/deps/uv/src/win/error.c#L167
