### ISSUE TITLE
sqs request error

### ISSUE THREAD

**Issue by james075** [bbc/sqs-consumer#12]
```bash
/xxxx/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
Error: Callback was already called.
    at /xxxx/node_modules/async/lib/async.js:30:31
    at /xxxx/node_modules/sqs-consumer/index.js:127:5
    at /xxxx/node_modules/async/lib/async.js:251:17
    at /xxxx/node_modules/async/lib/async.js:154:25
    at /xxxx/node_modules/async/lib/async.js:248:21
    at /xxxx/node_modules/async/lib/async.js:612:34
    at Response.<anonymous> (/xxxx/node_modules/sqs-consumer/index.js:141:5)
    at Request.<anonymous> (/xxxx/node_modules/aws-sdk/lib/request.js:353:18)
    at Request.callListeners (/xxxx/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/xxxx/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

```

Hi, does anyone have the same exception ?

**Comment by traverseDLP** [comment]
What's your code look like?

**Comment by robinjmurphy** [comment]
Could you post your code @james075?

**Comment by james075** [comment]
The implementation is simple as:

```js
Consumer.create({
  queueUrl: xxx,
  sqs: aws.sqs
  handleMessage: function (message, done) { 
    return done(); 
  });
})
.on('error', function (err) {
  console.log(err);
})
.start();
```

Also, I got another error linked to aws when I run the code above:

```bash
/xxx/node_modules/aws-sdk/lib/sequential_executor.js:29
      this._events[eventName].push(listener);
                              ^
TypeError: undefined is not a function
    at Request.on (/xxx/node_modules/aws-sdk/lib/sequential_executor.js:29:31)
    at Object.<anonymous> (/xxx/node_modules/aws-sdk/lib/sequential_executor.js:151:14)
    at Object.arrayEach (/xxx/node_modules/aws-sdk/lib/util.js:546:32)
    at Object.<anonymous> (/xxx/node_modules/aws-sdk/lib/sequential_executor.js:150:16)
    at Object.each (/xxx/node_modules/aws-sdk/lib/util.js:537:32)
    at Request.addListeners (/xxx/node_modules/aws-sdk/lib/sequential_executor.js:148:14)
    at addAllRequestListeners (/xxx/node_modules/aws-sdk/lib/service.js:222:28)
    at makeRequest (/xxx/node_modules/aws-sdk/lib/service.js:167:10)
    at svc.(anonymous function) [as receiveMessage] (/xxx/node_modules/aws-sdk/lib/service.js:418:21)
    at Consumer._poll (/xxx/node_modules/sqs-consumer/index.js:83:14)
```

**Comment by robinjmurphy** [comment]
Hmm that looks ok. It seems more like an AWS client error. Which version of Node are you using? I'll see if I can reproduce.

**Comment by neoadventist** [comment]
Anyone solve this?

**Comment by anistark** [comment]
Instead of :
`const Consumer = require('sqs-consumer');` 

Try: 
`const { Consumer } = require('sqs-consumer');`

**Comment by sanketh2222** [comment]
Thanks anistark, i was also facing same issue, thanks for the help
