### ISSUE TITLE
Any reason for: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by emorneau** [bbc/sqs-consumer#239]
We are getting this error. Any reason why such is happening?

{ SQSError: SQS receive message failed: Client network socket disconnected before secure TLS connection was established
at toSQSError (/app/node_modules/sqs-consumer/lib/consumer.js:40:20)
at Consumer._receiveMessage (/app/node_modules/sqs-consumer/lib/consumer.js:171:13)
at process._tickCallback (internal/process/next_tick.js:68:7)
name: 'SQSError',
code: 'NetworkingError',
statusCode: undefined,
region: 'us-east-1',
retryable: true,
hostname: 'sqs.us-east-1.amazonaws.com',
time: 2020-08-18T06:39:19.863Z }

**Comment by nspragg** [comment]
@emorneau - are you still getting this issue?
