### ISSUE TITLE
Error at Consumer._handleSqsResponse

### ISSUE THREAD

**Issue by mrminecart** [bbc/sqs-consumer#81]
I am getting the error below when I call .start();

```
/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error
    at Consumer._handleSqsResponse (/home/me/Documents/Repositories/my-sqs-listener/node_modules/sqs-consumer/index.js:124:24)
    at Request.<anonymous> (/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/me/Documents/Repositories/my-sqs-listener/node_modules/aws-sdk/lib/request.js:684:12)
```

Here is my code:
```
import debug from 'debug';
import Consumer from 'sqs-consumer';
import AWS from 'aws-sdk';

export class Queue {
    constructor(eventCallback) {
        this.debug = debug('gsl:lib/queue');
        this.debug('Loading...');

        AWS.config.update({
            region: 'eu-west-1',
            accessKeyId: 'KEY',
            secretAccessKey: 'ACCESS'
        });

        return Consumer.create({
            queueUrl: 'https://...my-sqs-service.fifo',
            handleMessage: eventCallback,
            sqs: new AWS.SQS()
        });
    }
}
```

```
import debug from 'debug';
import { Queue } from './lib/';

class App {
    constructor() {
        this.debug = debug('gsl:app');
        this.debug('Starting...');

        this.debug('Loading queue...');

        this.queue = new Queue(this.onMessage);
        this.queue.start();
    }

    onMessage(message, callback) {
        this.debug('Got new message!');
        this.debug(message);

        callback(null);
    }
}

global.app = new App();

```

**Comment by mrminecart** [comment]
Was a permissions issue in AWS.

I'll close this but perhaps better error messages would be nice.

Thanks!
