### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by naveenkerati** [bbc/sqs-consumer#95]
I have created a cluster process in and assigned one process to poll SQS. After processing message the worker process sends a message to Master process.send("Message"). But after that i am getting the following error.

```
Error: Callback was already called.
    at C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:903:32
    at C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:3858:13
    at handleMessage (C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\sqs-consumer\index.js:157:9)
    at C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:3853:24
    at replenish (C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:946:17)
    at C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:950:9
    at eachOfLimit (C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:975:24)
    at C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:980:16
    at _parallel (C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:3852:5)
    at Object.series (C:\Users\Naveen Kerati\Desktop\Node_Apps\node_modules\async\dist\async.js:4708:5)
```

**Comment by naveenkerati** [comment]
Please Help me I am stuck with this for 2 days now.

**Comment by nspragg** [comment]
This is not an error specific to **sqs-consumer**. Sounds like you've invoked the same callback more than once in your application.
